// ! Admin

const GET_ALL_USERS = "user:GET_ALL_USERS";
const DELETE_USER = "user:DELETE_USER";
const ADD_ADVER = "ADD_ADVER";
const GET_POST = "GET_POST"
const GET_PROFILE = "GET_PROFILE"  


//! user
const ADD_POST = "ADD_POST";
const ADD_COMMENTT = "ADD_COMMENT";
const ADD_LIEK = "ADD_LIEK";
const EDIT_POSTS = "user:EDIT_POSTS";
const ADD_REPORT = "user:ADD_REPORT";
const GET_ALL_POSTS = "user:GET_ALL_POSTS";
const GET_ADVER = "GET_ADVER";
const UPDATE_PASSWORD = "UPDATE_PASSWORD";
const UPDATE_PROFILE = "UPDATE_PROFILE";
const DELETE_POST ="DELETE_POST"
const POST_MY ="POST_MY"

// ! Sadmin

const ADD_ADMIN = "ADD_ADMIN";
const DELETE_ADMIN = "DELETE_ADMIN";
const GET_ALL_ADMIN = "GET_ALL_ADMIN";
const BLOCK_USER = "BLOCK_USER";
const GET_REPORT = "GET_REPORT";
const SOFT_DELET = "GET_REPORT";
const GET_ALL_USERS_SADMIN = "GET_ALL_USERS_SADMIN";






module.exports = {
    GET_ALL_USERS,
    GET_ALL_POSTS,
    DELETE_USER,
    EDIT_POSTS,
    ADD_ADVER,
    GET_ADVER,
    ADD_ADMIN,
    GET_ALL_ADMIN,
    DELETE_ADMIN,
    ADD_REPORT,
    ADD_POST,
    BLOCK_USER,
    GET_REPORT,
    SOFT_DELET,
    UPDATE_PASSWORD,
    UPDATE_PROFILE,
    GET_POST,
    DELETE_POST,
    GET_ALL_USERS_SADMIN,
    GET_PROFILE,
    ADD_COMMENTT,
    ADD_LIEK,
    POST_MY
}