const { GET_ALL_USERS, ADD_ADVER, GET_REPORT, BLOCK_USER, SOFT_DELET, UPDATE_PASSWORD, UPDATE_PROFILE, GET_POST, ADD_COMMENTT, ADD_LIEK , POST_MY} = require("../../../../modules/endpoints");


module.exports = [GET_ALL_USERS ,ADD_ADVER,GET_REPORT,BLOCK_USER,SOFT_DELET,UPDATE_PASSWORD , UPDATE_PROFILE,GET_POST,ADD_COMMENTT,ADD_LIEK ,POST_MY]