const {  ADD_ADMIN, GET_ALL_USERS, GET_ALL_ADMIN, DELETE_ADMIN, 
    GET_REPORT, BLOCK_USER, UPDATE_PASSWORD, UPDATE_PROFILE, GET_POST, EDIT_POSTS, GET_ALL_USERS_SADMIN, ADD_COMMENTT, ADD_LIEK ,POST_MY } = require("../../../../modules/endpoints");


module.exports = [GET_ALL_USERS ,ADD_ADMIN, GET_ALL_ADMIN , DELETE_ADMIN 
    ,GET_REPORT,BLOCK_USER,UPDATE_PASSWORD , UPDATE_PROFILE,GET_POST,EDIT_POSTS ,GET_ALL_USERS_SADMIN,ADD_COMMENTT,ADD_LIEK ,POST_MY]