const { GET_ALL_POSTS, EDIT_POSTS, GET_ADVER, ADD_REPORT, ADD_POST, 
    SOFT_DELET, UPDATE_PASSWORD, UPDATE_PROFILE, GET_POST, DELETE_POST, GET_PROFILE, ADD_COMMENTT, ADD_LIEK ,POST_MY} = require("../../../../modules/endpoints");


module.exports = [EDIT_POSTS , GET_ALL_POSTS, GET_ADVER , 
    ADD_REPORT , ADD_POST,SOFT_DELET,UPDATE_PASSWORD,
    UPDATE_PROFILE , GET_POST ,DELETE_POST,GET_PROFILE,ADD_COMMENTT,ADD_LIEK ,POST_MY]